app:
  env: 'local'
  port: 8888
  app_name: 'hanya-gin'
  app_url: 'http://127.0.0.1'
log:
  level: 'info'
  root_dir: './storage/logs'
  filename: 'app.log'
  format: ''
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 28
  compress: true
database:
  driver: 'mysql'
  host: '127.0.0.1'
  port: 3306 # 端口号
  database: 'hanya-gin'
  username: 'root'
  password: 'root'
  charset: 'utf8mb4'
  max_idle_conns: 5
  max_open_conns: 100
  log_mode: 'info'
  enable_file_log_writer: true
  log_filename: 'sql.log'
redis:
  host: '127.0.0.1'
  port: 6379
  db: 0
  password: ''
jwt:
  secret: 40de3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s
  ttl: 86400
  blacklist_grace_period: 10
storage:
  default: "local"
  disks:
    local:
      root_dir: "./storage/app"
      app_url: "http://localhost:8888/storage"
    ali_oss:
      access_key_id: ''
      access_key_secret: ''
      bucket: 'yscommon'
      endpoint: 'oss-cn-shanghai.aliyuncs.com'
      is_ssl: false
      is_private: false
    qi_niu:
      access_key: ''
      secret_key: ''
      bucket: 'cdn-yscase-com'
      domain: 'cdn.yscase.com'
      is_ssl: false
      is_private: false

